version: "3.8"

services:
  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - internal
    restart: always

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - internal
      - web
    restart: always

  # Vue.js Web Server (Securtest)
  securtest:
    image: securtest
    container_name: securtest
    networks:
      - internal
      - web
    restart: always

  # Shroombot API
  shroombot:
    image: shroombot
    container_name: shroombot
    env_file: ".env"
    volumes:
      - ./secret/mapping.bin:/mapping.bin
      - ./secret/.aiotdlib:/.aiotdlib
    networks:
      - internal
      - web
    restart: always

  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secret/ssl:/etc/nginx/ssl:ro # Assumes SSL certificates are stored here
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    restart: always

networks:
  internal:
    driver: bridge
  web:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
